language: node_js
node_js:
  - "4.2" 

env:
  global:
  - DEPLOY_BRANCH=master
  - secure: "UdIhbBbt2mIHkjlQR93v44LfRO+7oBoXuLEi1YGoLXZsE6veH9vnR6qMRBLwUDABZjjJHm1KqhYlkHmCOpChEKDzu+1k3h3DLzJlNKgZbYKA3SK5+IeDV32EvpSeTCWpS1e0i0+pOUdn4JJrWzKygnBn2tB/3XUJOU8xh1NIjR7ZXYGeh/y2Qd2Zfvvo0rnU0vQURHBmwLd1VscbxDiky+rP+PRwA25R4bSayTdHIiXsFDsRkGPkazPWh5+YzOM8Pr71xs4JPAtbUFESb99Ix+an1kqJCrRQm6Y3mIKZIeGacX+XsrGdN8R5B4gWFEStgKGNWncvll+7NSqQ/jMhwsasyI5V3Fsk/85cxCAN+yArKBBiVlJTGRUli3TsRJr3rLXQAlHpQEyQCido7L+4BOA6eWZPYa1PAstkkesxJ4qbtfKJEu9lqzmBkmxlhTqccNIthItFM38b9eYJ2xIbKQaZs3QgMQd42bwTyD88A1RbJvvUpRJNmdWNSAkNbUu23cIH7t8ZHqK9Jl92mE1KpgFTOALzIe9ap7vCP9fIxtlPzT9rtSCkm3cWSBOvBYLlpLj4UB8j3TlQJa+IfZJGHb6d/zx7W5BBQi8BuY+xqF1LvrEvMzrMTQQIX0jQV/2oIKf2/mvO/7h0vsOlREM9Ssh1AbJW9JNptjgRojIx63Q=" # GH_TOKEN

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/precalc.js

before_script:
- npm test
- node ./.build_scripts/precalc.js

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
