language: node_js
node_js:
  - "4.2"

env:
  global:
  - DEPLOY_BRANCH=master
  - secure: "zH83XQ1nLWk99Y6S8DrbdREvnmXR2tvt0ox5iNLUC2hiN1+cChlJIvWe/0Wx730oMR91+27HhzGuTdUD5bMb6IB10+TsNCoywy8u4f0unmG1LHbL61iltHPbxJixAWJpwEKbAFWJMxnVAJgP2bDo/BKeXXYuR07wPGC2HjEU22IPp+7Flnc3PxQOkFMmHTAvSRXf8ut86mhuYRnhldBwvg/4ARmP57zFcvk0Yi/rPR4TNNVaUgFbX9hMWu9PifF+sFZ45FWw2l8t9aWY1CE+IvHo8AjZnKzn+rWL83YFmPCKB5AaZWlo0gRZEKglk7v85TkC3ISig9xvvBpnEvtBW4VvZdHcOAzdr0NvAs6iizKfQH3WK0f72L9zI1lf1TFQahgT5FAbKXtIoUYq1FUW1rClzHJyMnfmfFeOl2mCWADRdE0aPwNsw/GrXPxazTGAmJQ+HJIr4y+tGMSeFmvxsOSRJwvFwCR22/d1XrEyqvecp+BSAjAa/RxBMOlnNmLrCjT5F03qze02xIItVdp/5bbCkBzli6Xyb308OGmHDylAehe2feEjJFPcJb+kLRJb952fYX7hft0tC0M2gfsfIESQrsMq3Q+NV30rrH106hf4LJPr8FWI8ekphJ9qczx1UWe8k+g2DWxZ6KWAdmczy6Y6O7EuaFjGJYINph3YeW8=" # GH_TOKEN

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/precalc.js

before_script:
- npm test
- node ./.build_scripts/precalc.js

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
